author = "mangkoran"
base_url = "https://blog.mangkoran.com"
build_search_index = false
compile_sass = false
taxonomies = [{ name = "tags" }]
theme = "foobar-zola"
title = "mangkoran's Blog"

[markdown]
highlight_code = false

[extra]
[extra.navigation]
items = [
  { text = "Home", url = "/" },
  { text = "Blog", url = "/blog/" },
  { text = "Log", url = "/log/" },
  # { name = "Tags", url = "/tags/" },
  { text = "Now", url = "/now/" },
  { text = "About", url = "/about/" },
]
